### ISSUE TITLE
Gnome-shell extension doesn't work as in the demo

### ISSUE THREAD

**Issue by icaruseffect** [screenfreeze/deskcon-desktop#1]
I'm running fedora 20 on my desktop (with gnome shellv version 3.10.2.1) and installed the desktop extension according to the readme. I'm running the newest version from github.
The icon is being displayed but there is no interaction with it possible. This means it doesn't react on any clicks.
I also tried to change the permissions of the extension.js to executable as in other (for me) working extensions.

**Comment by screenfreeze** [comment]
Hi, sry that you are having trouble with it. If the Icon is visible in the
status Menu, means (most of the Time) that the Extension is loaded
correctly.
For the Extension to work,
1. the Desktop Server must be started.
2. Also, a Device must be paired with this Desktop PC.
3. The Android Device must be on the same network.
4. The status updates must be enabled on that Device.

Did you do all that? Is your Firewall enabled?

I'll fix it as fast I can, if it is Bug related.

**Comment by icaruseffect** [comment]
Hi, thank you for the fast response. 
I did all the steps and also opened the port in my firewall. 
Also the connection seems to be working..  At least the desktop is shown is registered in the app.   Also I enabled the access to notifications for the app. 
I guess the default behavior of showing battery percentage and the other stats should work after connection. 
Update time is for testing purposes set on 2 (minutes I guess). 
The phone is running on cyanogenmod 11 nightly, so Android 4.4.2. 
If I can provide any logs I could help.

**Comment by icaruseffect** [comment]
I tried to look into the Java code of the extension but my knowledge is limited about Java but found no problems so far.

**Comment by screenfreeze** [comment]
If your Firewall is active, I think I know the issue. Mobile Device and Desktop establish first an insecure Connection then a secure TLS Connection which uses a different Port than the one in the Config File.
This port is 8026. So if your didn't change the Port, you need to open Ports 8082 and 8026 in your Firewall.It's a Bug from my Side. I will put it in the config File next time.

**Comment by icaruseffect** [comment]
Problem solved. 
Wouldn't it be easier to run the secured communication over the same port? Would save some trouble and you don't have to open more ports. 
Anyways thank you very much for the fast help.

**Comment by screenfreeze** [comment]
Glad I could help. Well, other Devices couldn't connect insecure to that Desktop, which is needed for the pairing.
I try to find a solution.
