### ISSUE TITLE
according to the news the lead developer was found dead in his car

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [screenfreeze/deskcon-desktop#23]

**Comment by Xylemon** [comment]
What? I need some proof before believing this...

**Comment by RonnyPfannschmidt** [comment]
https://blaulichtreport-saarland.de/2014/11/vermisst-andreas-wilhelm-27-aus-schwalbach/

and according to his site http://screenfreeze.net/about/ hes ANdreas W. from schwalbach, and doing comp sci
the town is rather small is the margin for error seems small, im not sure what to do

have you seen anything new from him after 09.11.?

**Comment by Xylemon** [comment]
I sent an email to "help@screenfreeze.net" but never got a reply. I figured it was just because the author was busy. I sure hope the author dying isn't the case here for the absence. Is there anyone who knew the author personally who could confirm whether he's alive or dead?

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell on google maps the authors hometown is a very small one, im not as optimistic as you, and i wonder how to handle and how to work on things

**Comment by RonnyPfannschmidt** [comment]
due to data protection laws the local police wont tell me if its the same person,
until this ticket is closed invalid i'll assume the worst happened

**Comment by kennux** [comment]
It is true, he died at the 9th November 2014.
I have been working with him for the past half year and our company took over his website http://www.screenfreeze.net

**Comment by mobilitysol** [comment]
Gracias por comunicarse!

Estare fuera de la oficina hasta el 24 de enero de 2015.

Si necesita comunicarse con la empresa puede hacerlo enviando un mail a las siguientes direcciones>
por temas administrativos a stefani@interclip.com
por temas tecnicos a ovilladeamigo@mobilitysol.com


Maxwell Banks
Mobility Solution
Francisco Araucho 1362 / 105
Tel: 2707 3795

**Comment by Xylemon** [comment]
@kennux This is very saddening news, my condolences. Thanks for the confirmation.

**Comment by haraldkrischner** [comment]
That's shocking and sad. :-/

**Comment by csvan** [comment]
Saw this though HN...very sad news indeed :( Condolences to his friends and family.

**Comment by nash-ye** [comment]
Condolences to his friends and family.

**Comment by EvgeniiFrolov** [comment]
Oh, that's bad.... So sorry to hear this...

**Comment by RonnyPfannschmidt** [comment]
@kennux thanks for the confirmation
Condolences to his friends and family.

Also any idea how his projects will continue (i wanted to start working on deskcon)

**Comment by EvgeniiFrolov** [comment]
Condolences to his friends and family.
What was the cause?

@RonnyPfannschmidt it would be great if anyone could continue this!

**Comment by RonnyPfannschmidt** [comment]
@EvgeniiFrolov i dont have the time take the project as lead
im hoping someone is willing to step up

**Comment by kennux** [comment]
I think one of you should step up as a new lead developer, fork this repository and go on with development in the new repository.

**Comment by tristan-k** [comment]
I would really appreciate further development. There are similar projects coming http://www.omgubuntu.co.uk/2015/03/new-app-brings-android-notifications-to-the-gnome-desktop

**Comment by topyli** [comment]
While I'm glad there's a more "official" GNOME effort towards this, they really are nowhere near deskcon yet. Last I heard, the developers didn't even know deskcon and linconnect exist, or even kde's well established framework. But yeah, this should be core GNOME stuff.

**Comment by LuccoJ** [comment]
@topyli plus the fact that it seems to be Bluetooth-based is a bit of a deal-breaker. These apps are useful when the phone is **away** from the computer, like, more than Bluetooth-range away. That's why DeskCon and similar systems used Wi-Fi, not Bluetooth...

**Comment by RonnyPfannschmidt** [comment]
closing to get if off my plate on github
