### ISSUE TITLE
Help getting it to work

### ISSUE THREAD

**Issue by pabgan** [screenfreeze/deskcon-desktop#8]
Hello.

I am very excited about this project and I would like to help if I can. However I can't seem to get it to work in my Fedora 20. Here is what I have done:

| 1. Set up an ad-hoc wifi connection between my laptop and my phone |
| --- |

pablo@fausto ~ % ifconfig
wlp2s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.42.0.1  netmask 255.255.255.0  broadcast 10.42.0.255
        inet6 fe80::c685:8ff:fe28:7ee5  prefixlen 64  scopeid 0x20<link>
        ether c4:85:08:28:7e:e5  txqueuelen 1000  (Ethernet)
- phone is 10.42.0.33 and ping to 10.42.0.1 is fine.

| 2. Get code |
| --- |
- Clone Android app and Desktop server code
- Copy extension to ~/.local/share/gnome-shell/extensions and activat it with gnome-tweak-tool

| 3. Set up server |
| --- |
- Configure server

pablo@fausto ~ % cat .deskcon/config.conf
[network]
port = 8082
secure_port = 8083
bindip = 10.42.0.1

[general]
download_dir = /home/pablo/Descargas
uuid = 919167740479234
debug = False

[permissions]
auto_accept_files = True
auto_open_urls = True
auto_store_clipboard = True
- Start server
  pablo@fausto ~/Workspace/git-projects/deskcon-desktop (git)-[master] % ./deskcon.sh
  Server started
- Start device setup on laptop through extension
- Check server
  pablo@fausto ~/.deskcon % ps aux | grep desk
  pablo     8132  0.0  0.0 113112  1368 pts/1    S+   11:28   0:00 /bin/bash ./deskcon.sh
  pablo     8134  0.0  0.6 636648 25888 pts/1    Sl+  11:28   0:00 /usr/bin/python ./deskcon-server
  pablo     8263  0.1  0.6 483496 27008 pts/1    Sl+  11:29   0:00 /usr/bin/python /home/pablo/Workspace/git-projects/deskcon-desktop/server/setupdevice.py

| 4. Disable firewall |
| --- |

pablo@fausto ~/Workspace/git-projects/deskcon-desktop (git)-[master] % sudo systemctl status firewalld.service  
firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled)
   Active: inactive (dead) since mar 2014-06-03 11:39:03 CEST; 35min ago
  Process: 804 ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS (code=exited, status=0/SUCCESS)
 Main PID: 804 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/firewalld.service

jun 03 09:23:24 fausto systemd[1]: Started firewalld - dynamic firewall daemon.
jun 03 11:39:02 fausto systemd[1]: Stopping firewalld - dynamic firewall da.....
jun 03 11:39:03 fausto systemd[1]: Stopped firewalld - dynamic firewall daemon.
Hint: Some lines were ellipsized, use -l to show in full.

| 5. Connect phone |
| --- |
- Compile app into phone.
- Start app and select Connection > Desktop Hosts > (+)
- Write:
  IP = 10.42.0.1
  Port = 8082
- Tap OK button.

| 6. Result |
| --- |
- Phone shows dialog: The pairing Process failed!
- I added to line 147 of AuthenticationManager.java:
  Log.e("cucu", "Error pairing: " + Host + ":" + Port, e);
- Logcat says:
  D/Pairing:(23018): start
  E/cucu(23018): Error pairing: 10.42.0.1:8082
  E/cucu(23018): java.net.ConnectException: failed to connect to /10.42.0.1 (port 8082): connect failed: ECONNREFUSED (Connection refused)

I have tried with different values for Bind IP in server configuration, but I do not know what it is.

Any hint?

Thank you very much for everything.

**Comment by screenfreeze** [comment]
Hi, I tried to reproduce the Error. I did everything you did and it worked fine. The only defference is I'm using Ubuntu.
Looks to me like, the port isn't opend or still blocked by a firewall. Also when you start the "Setup new Device" Dialog on your Laptop, you need to click forward until it says "waiting for connection ...".
Another possible problem could be that another program uses port 8082, in that case just change it in your config file. Let me if this helped :)

**Comment by pabgan** [comment]
Using 18082 port solved it, d'oh! Thanks. I was completely focused on the Bind IP thing, that I still do not know exactly what it is. Could you explain it to me?

I am going to play a bit with this, and in a few days I will write to you an email at help@screenfreeze.net to discuss some ideas, if you do not mind.
